<a href="https://colab.research.google.com/github/Ninkrn/BasicProg_Dataviz65/blob/main/Recap4_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix Slicing


In [ ]:
import numpy

In [ ]:
list_a = [[2,4,5],[1,2,3],[9,8,7],[3,6,9]]
mat_a = numpy.array(list_a)
mat_a

array([[2, 4, 5],
       [1, 2, 3],
       [9, 8, 7],
       [3, 6, 9]])

In [ ]:
import numpy as np

In [ ]:
list_b = [[-1,-1,2,4,5],[-2,-2,1,2,3],[-3,-3,9,8,7],[-4,-4,3,6,9]]
mat_b = np.array(list_b)
mat_b

array([[-1, -1,  2,  4,  5],
       [-2, -2,  1,  2,  3],
       [-3, -3,  9,  8,  7],
       [-4, -4,  3,  6,  9]])

## Quiz2
1. slice ค่าลบออกมาจาก mat_b
2. slice [1,2,3] จาก mat_a
3. slice [[1,3],[9,7],[3,9]] ออกมาจาก mat_b

In [ ]:
mat_b[:4,:2]

array([[-1, -1],
       [-2, -2],
       [-3, -3],
       [-4, -4]])

In [ ]:
mat_a[1]

array([1, 2, 3])

In [ ]:
mat_b[-3:,2::2]

array([[1, 3],
       [9, 7],
       [3, 9]])

## HW1

เขียน function
แสดงความต่างของเวลา (Quiz1)
โดย input อยู่ในรูปแบบ ```'09:11:50 - 12:30:15'```

และทดลองรัน

* '09:11:50 - 12:30:15'
* '13:41:07 - 20:00:18'
* '00:00:00 - 23:59:59'

In [8]:
def time_1(n1,n2,n3,N1,N2,N3):
    N = ((N1*3600) + (N2*60) + N3) - ((n1*3600) + (n2*60) + n3)
    return N

print(f'ความต่างของเวลา 09:11:50 - 12:30:15 คือ {time_1(9,11,50,12,30,15)} วินาที')

ความต่างของเวลา 09:11:50 - 12:30:15 คือ 11905 วินาที


In [9]:
def time_2(e1,e2,e3,E1,E2,E3):
    E = ((E1*3600) + (E2*60) + E3) - ((e1*3600) + (e2*60) + e3)
    return E

print(f'ความต่างของเวลา 13:41:07 - 20:00:18 คือ {time_1(13,41,7,20,0,18)} วินาที')

ความต่างของเวลา 13:41:07 - 20:00:18 คือ 22751 วินาที


In [10]:
def time_3(w1,w2,w3,W1,W2,W3):
    W = ((W*3600) + (W2*60) + W3) - ((w1*3600) + (w2*60) + w3)
    return W

print(f'ความต่างของเวลา 00:00:00 - 23:59:59 คือ {time_1(0,0,0,23,59,59)} วินาที')

ความต่างของเวลา 00:00:00 - 23:59:59 คือ 86399 วินาที


#Quiz3
เขียน function แสดงความต่างของเวลาโดย input อยู่ในรูปแบบ 'XX:YY:ZZ - AA:BB:CC'

และวนลูปแสดงผลของ input ต่อไปนี้

* '09:11:50 - 12:30:15'
* '13:41:07 - 20:00:18'
* '00:00:00 - 23:59:59'
* '18:04:11 - 00:00:00'  #+24hr.
* '21:30:00 - 03:05:15'

ตัวอย่าง input `'00:00:00-01:00:00'`

output `ช่วงระยะเวลาระหว่าง 00:00:00 ถึง 01:00:00 มีเวลาทั้งหมด 3,600 วินาที`

In [6]:
def calculate_time(time):
    t = time
    input_split = t.split('-')
    starttimeSP = input_split[0].split(':')
    endtimeSP = input_split[1].split(':')

    starttime = 3600*int(starttimeSP[0])+60*int(starttimeSP[1])+int(starttimeSP[2])
    endtime = 3600*int(endtimeSP[0])+60*int(endtimeSP[1])+int(endtimeSP[2])

    if endtime > starttime :
        print(f'ระยะเวลาระหว่าง {input_split[0]} ถึง {input_split[1]} มีเวลาทั้งหมด {endtime-starttime:,} วินาที')
    else:
        print(f'ระยะเวลาระหว่าง {input_split[0]} ถึง {input_split[1]} มีเวลาทั้งหมด {endtime+24*60*60 - starttime: ,} วินาที')

In [7]:
for time in ['09:11:50 - 12:30:15',
             '13:41:07 - 20:00:18',
             '00:00:00 - 23:59:59',
             '18:04:11 - 00:00:00',
             '21:30:00 - 03:05:15']:
    T = time
    calculate_time(T)

ระยะเวลาระหว่าง 09:11:50  ถึง  12:30:15 มีเวลาทั้งหมด 11,905 วินาที
ระยะเวลาระหว่าง 13:41:07  ถึง  20:00:18 มีเวลาทั้งหมด 22,751 วินาที
ระยะเวลาระหว่าง 00:00:00  ถึง  23:59:59 มีเวลาทั้งหมด 86,399 วินาที
ระยะเวลาระหว่าง 18:04:11  ถึง  00:00:00 มีเวลาทั้งหมด  21,349 วินาที
ระยะเวลาระหว่าง 21:30:00  ถึง  03:05:15 มีเวลาทั้งหมด  20,115 วินาที
